'''
Julia
- Obs: A questão pedia a utilização de uma precisão relativa e não absoluta.
'''
# -*- coding: utf-8 -*-
"""bissecao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oN-zrBo_B7Q4dLHL-2qvimYNvl_Do67
"""

'''
Esse programa calcula o valor da primeira raiz positiva da função f(x) = e^−x − sin((pi*x)/2)
Quando x está no intervalo de 0 e 4
'''
import matplotlib.pyplot as plt
import numpy as np
import sys

#Função definida na tarefa anterior
def funcao1(x):
  '''
  Essa função calcula a função  f(x) = e^−x − sin((pi*x)/2)
  return: f(x)
  '''
  y = np.exp(-x) - np.sin(np.pi*x/2)
  return y

x_ = np.linspace(0, 4)    # O eixo x no intervalo de x ∈ [0, 4]
y = funcao1(x_)            # y assumindo o valor da funcao em relação a x_
plt.ylabel('f(x)')
plt.title('Gráfico da função f(x) = e^−x − sin((pi*x)/2)')
plt.grid(True)
plt.plot(x_,y)
plt.show()

xmin = 0.25    #Intervalo escolhido através do gráfico
xmax = 0.5

interacoes = 100 
precisao = 1.e-7

fmin = funcao1(xmin)
fmax = funcao1(xmax)

nit = 0

if fmin*fmax > 0:                   #Parar o programa caso fmin*fmax >0
  print("Intervalo inadequado")
  sys.exit()
else:
  while abs(xmax - xmin) > precisao and nit < interacoes:      #Condições para o while funcionar
    media = (xmin + xmax)/2
    fmedio = funcao1(media)
    if fmin*fmedio < 0:                                        
      xmax = media
    else:
      xmin = media
    nit += 1
print ("O número de interaçẽos é %d e a raiz vale %f" %(nit,media))
