'''
nao indica o valor incial de x
'''
# -*- coding: utf-8 -*-
"""NR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rT66G7ggGRE10myoHXrQxJSSmLCmCzHd
"""

import matplotlib.pyplot as plt
import numpy as np

def funcao1(x):
  '''
  Essa função calcula a função  f(x) = e^−x − sin((pi*x)/2)
  return: f(x)
  '''
  y = np.exp(-x) - np.sin(np.pi*x/2)
  return y

x_ = np.linspace(0, 4)    # O eixo x no intervalo de x ∈ [0, 4]
y = funcao1(x_)            # y assumindo o valor da funcao em relação a x_
plt.ylabel('f(x)')
plt.title('Gráfico da função f(x) = e^−x − sin((pi*x)/2)')
plt.grid(True)
plt.plot(x_,y)
plt.show()

def derivada(x):
  '''
  Função que determina a derivada da funcao1
  return: derivada
  '''
  derivada_ = -np.exp(-x) - (np.cos((x*np.pi)/2)*(np.pi/2))
  return derivada_

xo_ = 0.4                          #Definir xi
delta = 1.e7
interacao = 100
precisao = 1.e-7

nit = 0

while abs(delta) > precisao and nit < interacao:      #Enquanto essas condições forem obedecidas
  x = xo_ - (funcao1(xo_)/derivada(xo_))
  delta = x - xo_
  xo_ = x

  nit += 1

print("O número de interações é %d e a raiz é %f" %(nit, xo_))
